### ISSUE TITLE
Installing Mac with Go from Homebrew.

### ISSUE THREAD

**Issue by MichaelDimmitt** [hoop33/roster#2]
Context See #1 
I believe this is the error you were mentioning - still present with updated install.
```bash
go get -u github.com/hoop33/roster
package github.com/hoop33/roster/pb: no Go files in /Users/michaeldimmitt/go/src/github.com/hoop33/roster/pb
package google.golang.org/grpc/grpclb/grpc_lb_v1/messages: cannot find package "google.golang.org/grpc/grpclb/grpc_lb_v1/messages" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/google.golang.org/grpc/grpclb/grpc_lb_v1/messages (from $GOROOT)
	/Users/michaeldimmitt/go/src/google.golang.org/grpc/grpclb/grpc_lb_v1/messages (from $GOPATH)
```
Wanted to bring attention two the two details from above, 
<b>no Go files in: hoop33/roster/pb</b>
<b>cannot find package "google.golang.org/grpc/grpclb/grpc_lb_v1/messages"</b>

additional details:
```bash
echo $GOPATH
$ /Users/michaeldimmitt/go
```
```bash
echo $PATH
$ :/usr/local/Cellar/go/1.10.3/bin:/Users/michaeldimmitt/go/bin
```

This will ultimately lead to:
```
make
$ for file in $(find . -type f -name '*.proto'); do protoc -I $(dirname $file) --go_out=plugins=grpc:$(dirname $file) $file; done
$ /bin/sh: protoc: command not found
$ /bin/sh: protoc: command not found
$ /bin/sh: protoc: command not found
$ /bin/sh: protoc: command not found
$ /bin/sh: protoc: command not found
$ make: *** [proto] Error 127
```

Let me know if you need more information for describing the issue.
```bash
ls go/src/github.com/hoop33/roster/pb/
$ players.proto
```
I manually put in these two commands but no same error present.
```bash
go get github.com/stormcat24/protodep
go get -u google.golang.org/grpc
```
Operating System Info: 

Mac OS Sierra 10.12.6
Processor 2.9 GHz Intel Core i7
MacBook Pro (13-inch, Mid 2012)

**Comment by MichaelDimmitt** [comment]
@hoop33, I figured it out; but had to perform a few steps.
## In order to get protoc recognized as a command on my computer:
1) `brew install protobuf` [source](https://stackoverflow.com/questions/21775151/installing-google-protocol-buffers-on-mac)

## In order to get grpc working correctly:
0) I had to install this guys go project: https://github.com/coredns/coredns
1) And copy the grpc from his vendor file.
2)
```bash
cd ~/go/src/github.com/hoop33/roster;
rm -rf vendor/google.golang.org/grpc; 
cp -rf ../../coredns/coredns/vendor/google.golang.org/grpc vendor/google.golang.org/grpc;
```

**Comment by MichaelDimmitt** [comment]
Full disclosure: your go other repos, Jags and Limo work with no issues.


Still getting an error apparently with additional vender dependencies. 
```
make && ./roster
for file in $(find . -type f -name '*.proto'); do protoc -I $(dirname $file) --go_out=plugins=grpc:$(dirname $file) $file; done
go vet github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
golint -set_exit_status github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
errcheck -exclude errcheck_excludes.txt github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
interfacer github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
aligncheck github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
structcheck github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
varcheck github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
unconvert -v github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
gosimple github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
staticcheck github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
unused github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
vendorcheck github.com/hoop33/roster github.com/hoop33/roster/models github.com/hoop33/roster/players
[!] dependency not vendored: github.com/golang/protobuf/proto
[!] dependency not vendored: google.golang.org/genproto/googleapis/rpc/status
[!] dependency not vendored: github.com/golang/protobuf/ptypes/any
[!] dependency not vendored: github.com/golang/protobuf/ptypes/timestamp
[!] dependency not vendored: github.com/golang/protobuf/ptypes/duration
make: *** [vendorcheck] Error 1
```

**Comment by hoop33** [comment]
For this error:

```sh
/bin/sh: protoc: command not found
```

That indicates that `protoc` is not installed or in your path, which is step 4 in the readme. Good to know that it's installable via homebrew; the gRPC installation page doesn't indicate that, but rather that you have to download a release, unzip it, and put the binary in your path. I've added the homebrew option to the readme.

The grpc issue indicates a mismatch between the libraries in the `vendor` folder and the ones that `protoc` is picking up. I've updated the libraries in the repo. Can you try pulling the latest repo?

Thanks for the feedback!

**Comment by MichaelDimmitt** [comment]
With:
dep ensure -update

And the other changes you have mentioned added to the readme.
Installation for a Mac computer is resolved on my end.

Closing the issue.
